apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30332
  selector:
    app: mongo
    tier: data
  type: NodePort
  # clusterIP: none
