apiVersion: v1
kind: Service
metadata:
  name: karsajobs
  labels:
    app: karsajobs
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30500
  selector:
    tier: backend
  type: NodePort
  # clusterIP: none
