apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
        - name: karsajobs-be
          image: sisaaref/karsajobs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: '8080'
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
